-- =============================================================================
-- File:    migrations/027_accounts_account_type_clinician.sql
-- Purpose: Widen the accounts.account_type CHECK constraint to allow
--          'clinician' alongside the existing 'patient' and 'delegate'.
--          Unblocks pharmacy clinician-origin writes (TLC-055 PR E onward)
--          by giving the accounts table a single source of truth for
--          clinician identity within a tenant.
--
-- Spec:    - RBAC v1.1 §1.2 (Clinician role; tenant-scoped per ADR-023)
--          - RBAC v1.1 §6 (Clinician role within multi-tenant context —
--            same physician in two tenants is two separate Clinician records)
--          - CDM v1.2 §3.2 (Account entity; account_type discriminator)
--          - Identity & Authentication Spec v1.0 §3.3 (access token claims;
--            role is derived from accounts.account_type)
--          - I-023 (clinicians are tenant-scoped; same FK pattern as patients)
--          - I-014 (canonical glossary: 'clinician' is the canonical role
--            name — not 'doctor', 'physician', 'provider')
--          - migrations/012_accounts.sql (target table)
--          - migrations/rollback/027_rollback.sql
--
-- HISTORY:
--   Migration 012 defined accounts with an inline UNNAMED CHECK constraint
--   on account_type that admitted only 'patient' and 'delegate' — the
--   v1.0 patient-app scope. PR D of the pharmacy slice (TLC-055 PR D)
--   surfaced this limitation: the medication_requests.prescribed_by_-
--   clinician_account_id composite FK targets accounts(tenant_id,
--   account_id) but no clinician account row could legitimately be
--   inserted, so the PR D test fixture had to reuse a 'patient'
--   account_type as the prescriber FK target. That stand-in is a fixture
--   hack; production prescriber accounts MUST be account_type='clinician'.
--
--   This migration corrects the durable boundary. The JWT layer
--   (src/lib/jwt.ts) and session-service (issueSession) are updated in
--   the same PR to widen ActorContext.role to 'patient' | 'clinician',
--   derive the role from accounts.account_type at session issuance time,
--   and validate the role enum at JWT verify time.
--
-- ADDED VALUES:
--   - 'clinician' — a tenant-scoped clinician account. Cross-tenant access
--     is never permitted (RBAC v1.1 §6); a physician operating across two
--     tenants holds two separate clinician accounts.
--
-- PRECONDITIONS:
--   migrations/012_accounts.sql applied (target table exists with the
--   prior CHECK constraint).
--
-- ROLLBACK:
--   migrations/rollback/027_rollback.sql
--
-- COMPAT:
--   Migration is non-destructive: no existing rows are modified. The
--   widened CHECK accepts every value the previous CHECK accepted plus
--   'clinician'. Clinician-role JWT issuance is a SEPARATE opt-in
--   (issueSession looks up account_type → resolves role), so an
--   account_type=clinician row in the DB alone does NOT change behavior
--   for any existing handler — handlers still authorize per role: 'patient'
--   today. PR E widens pharmacy handler authz to recognize role: 'clinician'.
-- =============================================================================

-- Migration 012 declared the CHECK inline without a name, so Postgres
-- assigned an auto-generated constraint name. The autogenerated name
-- pattern is `<table>_<column>_check` for a column-level CHECK; in this
-- repo we always use `<table>_<column>_check` as the canonical name.
-- Use IF EXISTS so the migration tolerates either the autogenerated or
-- the canonical name without surprises.

ALTER TABLE accounts
    DROP CONSTRAINT IF EXISTS accounts_account_type_check;

ALTER TABLE accounts
    ADD CONSTRAINT accounts_account_type_check CHECK (
        account_type IN ('patient', 'delegate', 'clinician')
    );

-- Index hint: callers that query accounts by tenant_id + account_type
-- (e.g., "list clinicians in this tenant" admin views) will land in PR E
-- or later. Adding a partial index here pre-emptively would be premature
-- (no consumer yet); add when the first query path needs it.

-- No backfill needed: every existing row has account_type ∈
-- {'patient', 'delegate'} from the prior CHECK, both of which remain
-- valid under the widened CHECK.
