SET LOCAL search_path=pg_catalog,public,pg_temp;
DROP TRIGGER IF EXISTS forms_publication_boundary ON public.forms_template;
DROP TRIGGER IF EXISTS forms_definition_immutable ON public.forms_published_definition;
DROP FUNCTION IF EXISTS public.forms_published_definition_immutable();
DROP FUNCTION IF EXISTS public.forms_enforce_publication();
DROP FUNCTION IF EXISTS public.forms_template_hash(public.forms_template);
DROP FUNCTION IF EXISTS public.forms_validate_presentation(JSONB,TEXT);
DROP FUNCTION IF EXISTS public.forms_safe_text(JSONB,INTEGER);
DROP FUNCTION IF EXISTS public.forms_require_keys(JSONB,TEXT[],TEXT[]);
DROP FUNCTION IF EXISTS public.forms_live_actor(TEXT);
DROP TABLE public.forms_published_definition,public.forms_governance_artifact,public.forms_governance_membership;
DROP OWNED BY forms_publication_owner;
DROP ROLE forms_publication_owner;
